### ISSUE TITLE
christian diff

### ISSUE THREAD

**Issue by jamesholbert** [alexmacarthur/christian-git#7]
`christian reform`?

**Comment by GabeMeister** [comment]
Yes.

**Comment by alexmacarthur** [comment]
Someone PR this!

**Comment by jamesholbert** [comment]
Permission denied :(

**Comment by alexmacarthur** [comment]
@jamesholbert Try forking the repo and making a pull request from your fork into my master branch.

**Comment by alexmacarthur** [comment]
Addressed with #10.
